name: Destroy All Infrastructure and Core
on:
  workflow_dispatch:

jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Infrastructure
        run: |
          az group delete --name mywr --no-wait