name: YAML Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install yamllint
      run: |
        pip install yamllint

    - name: Run yamllint
      run: |
        yamllint .
